trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  webSiteName: 'Default Web Site'
  siteSubfolder: 'Test_app' 
  AppPool: 'Test_app' # Nombre del pool de aplicaciones
  publishPath: '$(Build.ArtifactStagingDirectory)/drop'

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal'

  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(publishPath)'

  - task: ArchiveFiles@2
    displayName: 'Archive Published Files into ZIP'
    inputs:
      rootFolderOrFile: '$(publishPath)'   # Asegúrate de que esta ruta apunte a los archivos publicados
      includeRootFolder: false
      archiveFile: '$(publishPath)/$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(publishPath)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: Deploy
  displayName: 'Deploy to IIS'
  dependsOn: BuildAndPublish
  pool:
    name: 'AeroMxlServer'
   
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'

  - task: ExtractFiles@1
    displayName: 'Extract ZIP to Deployment Directory'
    inputs:
      archiveFilePatterns: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
      destinationFolder: '$(Pipeline.Workspace)/extracted'

  # Descomprime el ZIP dentro del ZIP
  - task: ExtractFiles@1
    displayName: 'Extract Inner ZIP'
    inputs:
      archiveFilePatterns: '$(Pipeline.Workspace)/extracted/*.zip'
      destinationFolder: '$(Pipeline.Workspace)/final_deploy'
  

  
  - task: IISWebAppDeploymentOnMachineGroup@0
    inputs:
      WebSiteName: '$(webSiteName)'
      VirtualApplication: '$(siteSubfolder)'  # Especifica la subcarpeta dentro del sitio web
      Package: '$(Pipeline.Workspace)/final_deploy'
      EnableMSDeployAppOffline: true  # Esta línea es clave
      TakeAppOfflineFlag: true
      XmlTransformation: true
      RemoveAdditionalFilesFlag: true
      AdditionalArguments: '-allowUntrusted'
  


- job: CleanUp
  displayName: 'Clean Up Temporary Files'
  dependsOn: Deploy
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      echo "Cleaning up temporary files..."
      if exist "$(Pipeline.Workspace)\drop" (
        rmdir /s /q "$(Pipeline.Workspace)\drop"
      ) else (
        echo "Drop directory does not exist."
      )
      if exist "$(Pipeline.Workspace)\extracted" (
        rmdir /s /q "$(Pipeline.Workspace)\extracted"
      ) else (
        echo "Extracted directory does not exist."
      )
      if exist "$(Pipeline.Workspace)\final_deploy" (
        rmdir /s /q "$(Pipeline.Workspace)\final_deploy"
      ) else (
        echo "Final deploy directory does not exist."
      )
    displayName: 'Remove Temporary Directories'